package com.qzx.au.extras;

public enum EnderButton {
	BUTTON_PLAYER_UD,
	BUTTON_PLAYER_NS,
	BUTTON_PLAYER_EW,
	BUTTON_DOWN,
	BUTTON_UP,
	BUTTON_NORTH,
	BUTTON_SOUTH,
	BUTTON_WEST,
	BUTTON_EAST,
	BUTTON_CONTROL_PLAYER,
	BUTTON_CONTROL_CONTACT,
	BUTTON_CONTROL_REDSTONE
}
