package com.qzx.au.tts;

public enum TTSButton {
	BUTTON_PLAYER_UD,
	BUTTON_PLAYER_NS,
	BUTTON_PLAYER_EW,
	BUTTON_DOWN,
	BUTTON_UP,
	BUTTON_NORTH,
	BUTTON_SOUTH,
	BUTTON_WEST,
	BUTTON_EAST,
	BUTTON_CONTROL_PLAYER,
	BUTTON_CONTROL_PLAYER_RS,
	BUTTON_CONTROL_REDSTONE,
	BUTTON_CONTROL_PLAYER_DEL,
	BUTTON_CONTROL_PLAYER_ADD
}
